// Category placeholder artwork.
//
// User-uploaded photos ALWAYS take priority (see ListingImage). These images are
// only shown when a listing/category has no real photo yet.
//
// TO INSTALL IMAGES: drop your files in public/placeholders/_incoming/ named by
// key (e.g. barber.webp) or by category (e.g. services.jpg), then run:
//     node scripts/install-placeholders.mjs
// That converts/places them and rewrites PLACEHOLDER_FILES below automatically.
// Any format works (.webp/.jpg/.png) — next/image serves optimized WebP either way.

/** All image keys the design expects (subjects documented in the README). */
export const PLACEHOLDER_KEYS = [
  "food-dishes", "food-vegetables", "food-market",
  "barber", "beauty-salon", "phone-repair", "carpenter",
  "motorbike-taxi", "taxi", "cargo-truck",
  "shop-storefront", "shop-market", "shop-retail",
  "home-modern", "apartment", "land",
  "car-sedan", "car-suv", "car-pickup",
  "smartphone", "electronics",
  "rental-home", "rental-equipment", "rental-vehicle",
  "jobs", "agriculture", "construction",
] as const;

/** Category id → placeholder image key. Unmapped categories use the neutral fallback. */
const CATEGORY_IMAGE: Record<string, string> = {
  // Food & agriculture
  rice: "food-dishes", drinks: "food-dishes", water: "food-dishes",
  "food-crops": "food-vegetables", vegetables: "food-vegetables", farm: "food-vegetables",
  "market-food": "food-market",
  // Services
  barber: "barber", "hair-braiding": "beauty-salon", "beauty-salon": "beauty-salon",
  "makeup-artist": "beauty-salon", "beauty-supply": "beauty-salon",
  "phone-repair": "phone-repair", "computer-repair": "phone-repair",
  carpentry: "carpenter", masonry: "carpenter", welding: "carpenter",
  // Transport
  motorbike: "motorbike-taxi", "motorbike-rental": "motorbike-taxi",
  taxi: "taxi", trucks: "cargo-truck", "truck-rental": "cargo-truck",
  // Shops & business
  restaurants: "shop-storefront", "cook-shops": "shop-storefront", "kobo-shops": "shop-storefront",
  "market-stalls": "shop-market", general: "shop-retail",
  // Real estate
  property: "home-modern",
  // Vehicles
  cars: "car-sedan",
  // Phones / electronics
  phones: "smartphone", electronics: "electronics",
  // Rentals
  "car-rental": "rental-vehicle", "equipment-rental": "rental-equipment",
  "house-rental": "rental-home", "bicycle-rental": "rental-vehicle",
  // Jobs / Agriculture / Construction / Beauty
  jobs: "jobs", "job-listings": "jobs",
  agriculture: "agriculture", livestock: "agriculture", "farm-produce": "agriculture",
  construction: "construction", "building-materials": "construction", plumbing: "construction",
  beauty: "beauty-salon", cosmetics: "beauty-salon",
};

// __PLACEHOLDER_FILES_START__ (auto-generated by scripts/install-placeholders.mjs — do not edit by hand)
export const PLACEHOLDER_FILES: Record<string, string> = {};
// __PLACEHOLDER_FILES_END__

/** Returns the placeholder image path for a category, or null to use the fallback. */
export function placeholderImage(category: string): string | null {
  const key = CATEGORY_IMAGE[category];
  const file = key ? PLACEHOLDER_FILES[key] : undefined;
  return file ? `/placeholders/${file}` : null;
}
